- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs-horizon
      - openstack-python35-jobs-horizon
      - openstack-python36-jobs-horizon
