- project:
    templates:
      - openstack-python-jobs-horizon
      - check-requirements
    check:
      jobs:
        - openstack-tox-lower-constraints
        - openstack-tox-py35:
            required-projects:
              - openstack/horizon
        - openstack-tox-py36:
            required-projects:
              - openstack/horizon
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - openstack-tox-py35:
            required-projects:
              - openstack/horizon
        - openstack-tox-py36:
            required-projects:
              - openstack/horizon
